enyo.depends(
    "src/grid.js",
    "src/version.js",
    "src/detector.js",
    "src/formatinf.js",
    "src/errorlevel.js",
    "src/bitmat.js",
    "src/datablock.js",
    "src/bmparser.js",
    "src/datamask.js",
    "src/rsdecoder.js",
    "src/gf256poly.js",
    "src/gf256.js",
    "src/decoder.js",
    "src/qrcode.js",
    "src/findpat.js",
    "src/alignpat.js",
    "src/databr.js"
);
